name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=2.0.1
  - ipython=7.21.0
  - notebook=6.2.0
  - jupyterlab=3.0.10
  - cookiecutter=2.1.0
  - hydra-core=1.0.6
  - matplotlib=3.6.2
  - pandas=1.5.2
  - git=2.30.2
  - pip=22.3.1
  - pip:
      - wandb==0.13.7